services:
  postgres:
    image: postgres:18
    container_name: booknest_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: huy
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: booknest_db
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: booknest_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
